[tool.poetry]
name = "dimorphite_dl"
version = "1.2.4"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
